package uk.fallingsloth.mc.items;

import net.fabricmc.fabric.api.item.v1.FabricItemSettings;
import net.minecraft.item.*;
import net.minecraft.registry.Registries;
import net.minecraft.registry.Registry;
import net.minecraft.util.Identifier;
import uk.fallingsloth.mc.Kingdoms;

/* THIS FILE IS AUTOMATICALLY GENERATED
   ANY MANUAL CHANGES WILL BE LOST
*/

public class ModItems
{
    /*
    Items to duplicate for each kingdom:
    - Sword
    - Pickaxe
    - Axe
    - Shovel
    - Hoe
    - Bow
    - Crossbow
    - Shield
    - Helmet
    - Chestplate
    - Leggings
    - Boots
    - Elytra
    - Trident
    - Fishing Rod
    */

    public static final Item GOLD_COIN = registerItem("gold_coin", new Item(new FabricItemSettings()));

//%KINGDOM_ITEMS%

    private static Item registerItem(String name, Item item)
    {
        return Registry.register(Registries.ITEM, new Identifier(Kingdoms.MOD_ID, name), item);
    }

    public static void registerModItems()
    {
        Kingdoms.LOGGER.info("Registering items for " + Kingdoms.MOD_ID);
    }
}
