package uk.fallingsloth.mc.items;

import net.fabricmc.fabric.api.item.v1.FabricItemSettings;
import net.minecraft.item.*;
import net.minecraft.registry.Registries;
import net.minecraft.registry.Registry;
import net.minecraft.util.Identifier;
import uk.fallingsloth.mc.Kingdoms;

/* THIS FILE IS AUTOMATICALLY GENERATED
   ANY MANUAL CHANGES WILL BE LOST
*/

public class ModItems
{
    /*
    Items to duplicate for each kingdom:
    - Sword
    - Pickaxe
    - Axe
    - Shovel
    - Hoe
    - Bow
    - Crossbow
    - Shield
    - Helmet
    - Chestplate
    - Leggings
    - Boots
    - Elytra
    - Trident
    - Fishing Rod
    */

    public static final Item GOLD_COIN = registerItem("gold_coin", new Item(new FabricItemSettings()));

    // ITEMS FOR KINGDOM 1
    public static final Item KINGDOM1_ESSENCE = registerItem("kingdom1_essence", new Item(new FabricItemSettings().maxCount(16)));
    public static final Item KINGDOM1_SWORD = registerItem("kingdom1_sword", new SwordItem(ToolMaterials.NETHERITE, 3, -2.4f, new FabricItemSettings()));
    public static final Item KINGDOM1_SHIELD = registerItem("kingdom1_shield", new ShieldItem(new FabricItemSettings()));
    public static final Item KINGDOM1_BOW = registerItem("kingdom1_bow", new BowItem(new FabricItemSettings()));
    public static final Item KINGDOM1_HELMET = registerItem("kingdom1_helmet", new ArmorItem(ArmorMaterials.NETHERITE, ArmorItem.Type.HELMET, new FabricItemSettings()));
    public static final Item KINGDOM1_CHESTPLATE = registerItem("kingdom1_chestplate", new ArmorItem(ArmorMaterials.NETHERITE, ArmorItem.Type.CHESTPLATE, new FabricItemSettings()));
    public static final Item KINGDOM1_LEGGINGS = registerItem("kingdom1_leggings", new ArmorItem(ArmorMaterials.NETHERITE, ArmorItem.Type.LEGGINGS, new FabricItemSettings()));
    public static final Item KINGDOM1_BOOTS = registerItem("kingdom1_boots", new ArmorItem(ArmorMaterials.NETHERITE, ArmorItem.Type.BOOTS, new FabricItemSettings()));

    // ITEMS FOR KINGDOM 2
    public static final Item KINGDOM2_ESSENCE = registerItem("kingdom2_essence", new Item(new FabricItemSettings().maxCount(16)));
    public static final Item KINGDOM2_SWORD = registerItem("kingdom2_sword", new SwordItem(ToolMaterials.NETHERITE, 3, -2.4f, new FabricItemSettings()));
    public static final Item KINGDOM2_SHIELD = registerItem("kingdom2_shield", new ShieldItem(new FabricItemSettings()));
    public static final Item KINGDOM2_BOW = registerItem("kingdom2_bow", new BowItem(new FabricItemSettings()));
    public static final Item KINGDOM2_HELMET = registerItem("kingdom2_helmet", new ArmorItem(ArmorMaterials.NETHERITE, ArmorItem.Type.HELMET, new FabricItemSettings()));
    public static final Item KINGDOM2_CHESTPLATE = registerItem("kingdom2_chestplate", new ArmorItem(ArmorMaterials.NETHERITE, ArmorItem.Type.CHESTPLATE, new FabricItemSettings()));
    public static final Item KINGDOM2_LEGGINGS = registerItem("kingdom2_leggings", new ArmorItem(ArmorMaterials.NETHERITE, ArmorItem.Type.LEGGINGS, new FabricItemSettings()));
    public static final Item KINGDOM2_BOOTS = registerItem("kingdom2_boots", new ArmorItem(ArmorMaterials.NETHERITE, ArmorItem.Type.BOOTS, new FabricItemSettings()));

    // ITEMS FOR KINGDOM 3
    public static final Item KINGDOM3_ESSENCE = registerItem("kingdom3_essence", new Item(new FabricItemSettings().maxCount(16)));
    public static final Item KINGDOM3_SWORD = registerItem("kingdom3_sword", new SwordItem(ToolMaterials.NETHERITE, 3, -2.4f, new FabricItemSettings()));
    public static final Item KINGDOM3_SHIELD = registerItem("kingdom3_shield", new ShieldItem(new FabricItemSettings()));
    public static final Item KINGDOM3_BOW = registerItem("kingdom3_bow", new BowItem(new FabricItemSettings()));
    public static final Item KINGDOM3_HELMET = registerItem("kingdom3_helmet", new ArmorItem(ArmorMaterials.NETHERITE, ArmorItem.Type.HELMET, new FabricItemSettings()));
    public static final Item KINGDOM3_CHESTPLATE = registerItem("kingdom3_chestplate", new ArmorItem(ArmorMaterials.NETHERITE, ArmorItem.Type.CHESTPLATE, new FabricItemSettings()));
    public static final Item KINGDOM3_LEGGINGS = registerItem("kingdom3_leggings", new ArmorItem(ArmorMaterials.NETHERITE, ArmorItem.Type.LEGGINGS, new FabricItemSettings()));
    public static final Item KINGDOM3_BOOTS = registerItem("kingdom3_boots", new ArmorItem(ArmorMaterials.NETHERITE, ArmorItem.Type.BOOTS, new FabricItemSettings()));

    // ITEMS FOR KINGDOM 4
    public static final Item KINGDOM4_ESSENCE = registerItem("kingdom4_essence", new Item(new FabricItemSettings().maxCount(16)));
    public static final Item KINGDOM4_SWORD = registerItem("kingdom4_sword", new SwordItem(ToolMaterials.NETHERITE, 3, -2.4f, new FabricItemSettings()));
    public static final Item KINGDOM4_SHIELD = registerItem("kingdom4_shield", new ShieldItem(new FabricItemSettings()));
    public static final Item KINGDOM4_BOW = registerItem("kingdom4_bow", new BowItem(new FabricItemSettings()));
    public static final Item KINGDOM4_HELMET = registerItem("kingdom4_helmet", new ArmorItem(ArmorMaterials.NETHERITE, ArmorItem.Type.HELMET, new FabricItemSettings()));
    public static final Item KINGDOM4_CHESTPLATE = registerItem("kingdom4_chestplate", new ArmorItem(ArmorMaterials.NETHERITE, ArmorItem.Type.CHESTPLATE, new FabricItemSettings()));
    public static final Item KINGDOM4_LEGGINGS = registerItem("kingdom4_leggings", new ArmorItem(ArmorMaterials.NETHERITE, ArmorItem.Type.LEGGINGS, new FabricItemSettings()));
    public static final Item KINGDOM4_BOOTS = registerItem("kingdom4_boots", new ArmorItem(ArmorMaterials.NETHERITE, ArmorItem.Type.BOOTS, new FabricItemSettings()));

    // ITEMS FOR KINGDOM 5
    public static final Item KINGDOM5_ESSENCE = registerItem("kingdom5_essence", new Item(new FabricItemSettings().maxCount(16)));
    public static final Item KINGDOM5_SWORD = registerItem("kingdom5_sword", new SwordItem(ToolMaterials.NETHERITE, 3, -2.4f, new FabricItemSettings()));
    public static final Item KINGDOM5_SHIELD = registerItem("kingdom5_shield", new ShieldItem(new FabricItemSettings()));
    public static final Item KINGDOM5_BOW = registerItem("kingdom5_bow", new BowItem(new FabricItemSettings()));
    public static final Item KINGDOM5_HELMET = registerItem("kingdom5_helmet", new ArmorItem(ArmorMaterials.NETHERITE, ArmorItem.Type.HELMET, new FabricItemSettings()));
    public static final Item KINGDOM5_CHESTPLATE = registerItem("kingdom5_chestplate", new ArmorItem(ArmorMaterials.NETHERITE, ArmorItem.Type.CHESTPLATE, new FabricItemSettings()));
    public static final Item KINGDOM5_LEGGINGS = registerItem("kingdom5_leggings", new ArmorItem(ArmorMaterials.NETHERITE, ArmorItem.Type.LEGGINGS, new FabricItemSettings()));
    public static final Item KINGDOM5_BOOTS = registerItem("kingdom5_boots", new ArmorItem(ArmorMaterials.NETHERITE, ArmorItem.Type.BOOTS, new FabricItemSettings()));

    // ITEMS FOR KINGDOM 6
    public static final Item KINGDOM6_ESSENCE = registerItem("kingdom6_essence", new Item(new FabricItemSettings().maxCount(16)));
    public static final Item KINGDOM6_SWORD = registerItem("kingdom6_sword", new SwordItem(ToolMaterials.NETHERITE, 3, -2.4f, new FabricItemSettings()));
    public static final Item KINGDOM6_SHIELD = registerItem("kingdom6_shield", new ShieldItem(new FabricItemSettings()));
    public static final Item KINGDOM6_BOW = registerItem("kingdom6_bow", new BowItem(new FabricItemSettings()));
    public static final Item KINGDOM6_HELMET = registerItem("kingdom6_helmet", new ArmorItem(ArmorMaterials.NETHERITE, ArmorItem.Type.HELMET, new FabricItemSettings()));
    public static final Item KINGDOM6_CHESTPLATE = registerItem("kingdom6_chestplate", new ArmorItem(ArmorMaterials.NETHERITE, ArmorItem.Type.CHESTPLATE, new FabricItemSettings()));
    public static final Item KINGDOM6_LEGGINGS = registerItem("kingdom6_leggings", new ArmorItem(ArmorMaterials.NETHERITE, ArmorItem.Type.LEGGINGS, new FabricItemSettings()));
    public static final Item KINGDOM6_BOOTS = registerItem("kingdom6_boots", new ArmorItem(ArmorMaterials.NETHERITE, ArmorItem.Type.BOOTS, new FabricItemSettings()));

    // ITEMS FOR KINGDOM 7
    public static final Item KINGDOM7_ESSENCE = registerItem("kingdom7_essence", new Item(new FabricItemSettings().maxCount(16)));
    public static final Item KINGDOM7_SWORD = registerItem("kingdom7_sword", new SwordItem(ToolMaterials.NETHERITE, 3, -2.4f, new FabricItemSettings()));
    public static final Item KINGDOM7_SHIELD = registerItem("kingdom7_shield", new ShieldItem(new FabricItemSettings()));
    public static final Item KINGDOM7_BOW = registerItem("kingdom7_bow", new BowItem(new FabricItemSettings()));
    public static final Item KINGDOM7_HELMET = registerItem("kingdom7_helmet", new ArmorItem(ArmorMaterials.NETHERITE, ArmorItem.Type.HELMET, new FabricItemSettings()));
    public static final Item KINGDOM7_CHESTPLATE = registerItem("kingdom7_chestplate", new ArmorItem(ArmorMaterials.NETHERITE, ArmorItem.Type.CHESTPLATE, new FabricItemSettings()));
    public static final Item KINGDOM7_LEGGINGS = registerItem("kingdom7_leggings", new ArmorItem(ArmorMaterials.NETHERITE, ArmorItem.Type.LEGGINGS, new FabricItemSettings()));
    public static final Item KINGDOM7_BOOTS = registerItem("kingdom7_boots", new ArmorItem(ArmorMaterials.NETHERITE, ArmorItem.Type.BOOTS, new FabricItemSettings()));

    // ITEMS FOR KINGDOM 8
    public static final Item KINGDOM8_ESSENCE = registerItem("kingdom8_essence", new Item(new FabricItemSettings().maxCount(16)));
    public static final Item KINGDOM8_SWORD = registerItem("kingdom8_sword", new SwordItem(ToolMaterials.NETHERITE, 3, -2.4f, new FabricItemSettings()));
    public static final Item KINGDOM8_SHIELD = registerItem("kingdom8_shield", new ShieldItem(new FabricItemSettings()));
    public static final Item KINGDOM8_BOW = registerItem("kingdom8_bow", new BowItem(new FabricItemSettings()));
    public static final Item KINGDOM8_HELMET = registerItem("kingdom8_helmet", new ArmorItem(ArmorMaterials.NETHERITE, ArmorItem.Type.HELMET, new FabricItemSettings()));
    public static final Item KINGDOM8_CHESTPLATE = registerItem("kingdom8_chestplate", new ArmorItem(ArmorMaterials.NETHERITE, ArmorItem.Type.CHESTPLATE, new FabricItemSettings()));
    public static final Item KINGDOM8_LEGGINGS = registerItem("kingdom8_leggings", new ArmorItem(ArmorMaterials.NETHERITE, ArmorItem.Type.LEGGINGS, new FabricItemSettings()));
    public static final Item KINGDOM8_BOOTS = registerItem("kingdom8_boots", new ArmorItem(ArmorMaterials.NETHERITE, ArmorItem.Type.BOOTS, new FabricItemSettings()));

    // ITEMS FOR KINGDOM 9
    public static final Item KINGDOM9_ESSENCE = registerItem("kingdom9_essence", new Item(new FabricItemSettings().maxCount(16)));
    public static final Item KINGDOM9_SWORD = registerItem("kingdom9_sword", new SwordItem(ToolMaterials.NETHERITE, 3, -2.4f, new FabricItemSettings()));
    public static final Item KINGDOM9_SHIELD = registerItem("kingdom9_shield", new ShieldItem(new FabricItemSettings()));
    public static final Item KINGDOM9_BOW = registerItem("kingdom9_bow", new BowItem(new FabricItemSettings()));
    public static final Item KINGDOM9_HELMET = registerItem("kingdom9_helmet", new ArmorItem(ArmorMaterials.NETHERITE, ArmorItem.Type.HELMET, new FabricItemSettings()));
    public static final Item KINGDOM9_CHESTPLATE = registerItem("kingdom9_chestplate", new ArmorItem(ArmorMaterials.NETHERITE, ArmorItem.Type.CHESTPLATE, new FabricItemSettings()));
    public static final Item KINGDOM9_LEGGINGS = registerItem("kingdom9_leggings", new ArmorItem(ArmorMaterials.NETHERITE, ArmorItem.Type.LEGGINGS, new FabricItemSettings()));
    public static final Item KINGDOM9_BOOTS = registerItem("kingdom9_boots", new ArmorItem(ArmorMaterials.NETHERITE, ArmorItem.Type.BOOTS, new FabricItemSettings()));

    // ITEMS FOR KINGDOM 10
    public static final Item KINGDOM10_ESSENCE = registerItem("kingdom10_essence", new Item(new FabricItemSettings().maxCount(16)));
    public static final Item KINGDOM10_SWORD = registerItem("kingdom10_sword", new SwordItem(ToolMaterials.NETHERITE, 3, -2.4f, new FabricItemSettings()));
    public static final Item KINGDOM10_SHIELD = registerItem("kingdom10_shield", new ShieldItem(new FabricItemSettings()));
    public static final Item KINGDOM10_BOW = registerItem("kingdom10_bow", new BowItem(new FabricItemSettings()));
    public static final Item KINGDOM10_HELMET = registerItem("kingdom10_helmet", new ArmorItem(ArmorMaterials.NETHERITE, ArmorItem.Type.HELMET, new FabricItemSettings()));
    public static final Item KINGDOM10_CHESTPLATE = registerItem("kingdom10_chestplate", new ArmorItem(ArmorMaterials.NETHERITE, ArmorItem.Type.CHESTPLATE, new FabricItemSettings()));
    public static final Item KINGDOM10_LEGGINGS = registerItem("kingdom10_leggings", new ArmorItem(ArmorMaterials.NETHERITE, ArmorItem.Type.LEGGINGS, new FabricItemSettings()));
    public static final Item KINGDOM10_BOOTS = registerItem("kingdom10_boots", new ArmorItem(ArmorMaterials.NETHERITE, ArmorItem.Type.BOOTS, new FabricItemSettings()));

    // ITEMS FOR KINGDOM 11
    public static final Item KINGDOM11_ESSENCE = registerItem("kingdom11_essence", new Item(new FabricItemSettings().maxCount(16)));
    public static final Item KINGDOM11_SWORD = registerItem("kingdom11_sword", new SwordItem(ToolMaterials.NETHERITE, 3, -2.4f, new FabricItemSettings()));
    public static final Item KINGDOM11_SHIELD = registerItem("kingdom11_shield", new ShieldItem(new FabricItemSettings()));
    public static final Item KINGDOM11_BOW = registerItem("kingdom11_bow", new BowItem(new FabricItemSettings()));
    public static final Item KINGDOM11_HELMET = registerItem("kingdom11_helmet", new ArmorItem(ArmorMaterials.NETHERITE, ArmorItem.Type.HELMET, new FabricItemSettings()));
    public static final Item KINGDOM11_CHESTPLATE = registerItem("kingdom11_chestplate", new ArmorItem(ArmorMaterials.NETHERITE, ArmorItem.Type.CHESTPLATE, new FabricItemSettings()));
    public static final Item KINGDOM11_LEGGINGS = registerItem("kingdom11_leggings", new ArmorItem(ArmorMaterials.NETHERITE, ArmorItem.Type.LEGGINGS, new FabricItemSettings()));
    public static final Item KINGDOM11_BOOTS = registerItem("kingdom11_boots", new ArmorItem(ArmorMaterials.NETHERITE, ArmorItem.Type.BOOTS, new FabricItemSettings()));

    // ITEMS FOR KINGDOM 12
    public static final Item KINGDOM12_ESSENCE = registerItem("kingdom12_essence", new Item(new FabricItemSettings().maxCount(16)));
    public static final Item KINGDOM12_SWORD = registerItem("kingdom12_sword", new SwordItem(ToolMaterials.NETHERITE, 3, -2.4f, new FabricItemSettings()));
    public static final Item KINGDOM12_SHIELD = registerItem("kingdom12_shield", new ShieldItem(new FabricItemSettings()));
    public static final Item KINGDOM12_BOW = registerItem("kingdom12_bow", new BowItem(new FabricItemSettings()));
    public static final Item KINGDOM12_HELMET = registerItem("kingdom12_helmet", new ArmorItem(ArmorMaterials.NETHERITE, ArmorItem.Type.HELMET, new FabricItemSettings()));
    public static final Item KINGDOM12_CHESTPLATE = registerItem("kingdom12_chestplate", new ArmorItem(ArmorMaterials.NETHERITE, ArmorItem.Type.CHESTPLATE, new FabricItemSettings()));
    public static final Item KINGDOM12_LEGGINGS = registerItem("kingdom12_leggings", new ArmorItem(ArmorMaterials.NETHERITE, ArmorItem.Type.LEGGINGS, new FabricItemSettings()));
    public static final Item KINGDOM12_BOOTS = registerItem("kingdom12_boots", new ArmorItem(ArmorMaterials.NETHERITE, ArmorItem.Type.BOOTS, new FabricItemSettings()));

    // ITEMS FOR KINGDOM 13
    public static final Item KINGDOM13_ESSENCE = registerItem("kingdom13_essence", new Item(new FabricItemSettings().maxCount(16)));
    public static final Item KINGDOM13_SWORD = registerItem("kingdom13_sword", new SwordItem(ToolMaterials.NETHERITE, 3, -2.4f, new FabricItemSettings()));
    public static final Item KINGDOM13_SHIELD = registerItem("kingdom13_shield", new ShieldItem(new FabricItemSettings()));
    public static final Item KINGDOM13_BOW = registerItem("kingdom13_bow", new BowItem(new FabricItemSettings()));
    public static final Item KINGDOM13_HELMET = registerItem("kingdom13_helmet", new ArmorItem(ArmorMaterials.NETHERITE, ArmorItem.Type.HELMET, new FabricItemSettings()));
    public static final Item KINGDOM13_CHESTPLATE = registerItem("kingdom13_chestplate", new ArmorItem(ArmorMaterials.NETHERITE, ArmorItem.Type.CHESTPLATE, new FabricItemSettings()));
    public static final Item KINGDOM13_LEGGINGS = registerItem("kingdom13_leggings", new ArmorItem(ArmorMaterials.NETHERITE, ArmorItem.Type.LEGGINGS, new FabricItemSettings()));
    public static final Item KINGDOM13_BOOTS = registerItem("kingdom13_boots", new ArmorItem(ArmorMaterials.NETHERITE, ArmorItem.Type.BOOTS, new FabricItemSettings()));



    private static Item registerItem(String name, Item item)
    {
        return Registry.register(Registries.ITEM, new Identifier(Kingdoms.MOD_ID, name), item);
    }

    public static void registerModItems()
    {
        Kingdoms.LOGGER.info("Registering items for " + Kingdoms.MOD_ID);
    }
}
